### ISSUE TITLE
Not working on raspberry 3b

### ISSUE THREAD

**Issue by createskyblue** [alex-s-v/10moons-driver#1]
Connect to the digital board. Follow the prompts to complete all operations. The running system prompts that the USB is disconnected
The pen did not respond, including the key on the T503.
There is no error in the python

**Comment by alex-s-v** [comment]
Sadly I don't have Raspberry Pi on my own, but if you are willing to cooperate we can tackle this problem, probably.

If I understood correctly your device detects tablet on its own (you can check it with _lsusb_ command you should have something like this in the output:
`Bus 001 Device 055: ID 08f2:6811 Gotop Information Inc. [T503] Driver Inside Tablet`
).

I need to know if your vendor and product id are the same as mine. If not then you need to change these values to yours in config.yaml file, and if they are the same further investigations will be needed.

**Comment by createskyblue** [comment]
`Bus 001 Device 055: ID 08f2:6811 Gotop Information Inc. [T503] Driver Inside Tablet`
is correct

After executing the driver, the system notifies that 'T503' has been safely uninstalled
BUT,This will not be the case if you change the device ID in 'config.yaml'

**Comment by createskyblue** [comment]
If you are free, I can open VNC remote, so that we can conduct remote debugging

**Comment by alex-s-v** [comment]
Can you put [this file](https://gist.github.com/alex-s-v/073345ebbc5fca63894d89e5cbaed82e) into the folder with the driver, run it with sudo privileges and take a look at what it gives? If device is detected correctly it will display some information and if you move the pen on the tablet you shell see byte arrays appearing on the screen. If you will see what I stated here, then the problem is probably with evdev library if you see nothing or something unexpected then the problem is probably with the connection with the tablet or different data stream properties.

**Comment by createskyblue** [comment]
I'm trying to run test.py
The first two print statements report an error, and I make some changes
`
print({len(dev[0].interfaces())})
print({len(dev[0].interfaces()[i].endpoints())})
`
Successfully output some pen position data and key data，Such as:
`
DEVICE ID 08f2:6811 on Bus 001 Address 004 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x110 USB 1.1
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :    0x8 (8 bytes)
 idVendor               : 0x08f2
 idProduct              : 0x6811
 bcdDevice              : 0x1811 Device 24.11
 iManufacturer          :    0x1 SZ PING-IT INC. 
 iProduct               :    0x2 [T503] Driver Inside Tablet
 iSerialNumber          :    0x3 Internal CDROM 
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 100 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x52 (82 bytes)
   bNumInterfaces       :    0x3
   bConfigurationValue  :    0x1
   iConfiguration       :    0x3 Internal CDROM 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :   0x32 (100 mA)
    INTERFACE 0: Mass Storage ==============================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0x8 Mass Storage
     bInterfaceSubClass :    0x6
     bInterfaceProtocol :   0x50
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
      ENDPOINT 0x2: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
    INTERFACE 1: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x83: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
    INTERFACE 2: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x2
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x85: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x85 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0x8 (8 bytes)
       bInterval        :    0x1
set([3])
(<INTERFACE 0: Mass Storage>, <INTERFACE 1: Human Interface Device>, <INTERFACE 2: Human Interface Device>)
set([2])
(<ENDPOINT 0x81: Bulk IN>, <ENDPOINT 0x2: Bulk OUT>)
set([1])
(<ENDPOINT 0x83: Interrupt IN>,)
set([1])
(<ENDPOINT 0x85: Interrupt IN>,)
array('B', [5, 192, 94, 3, 109, 4, 0, 0])
`
But the driver is still unavailable

**Comment by createskyblue** [comment]
It is certain that the test program successfully reads the data on 'T503'

**Comment by alex-s-v** [comment]
Can you try [this fork](https://github.com/jgobi/10moons-driver-t503) of my repo. [jgobi said](https://github.com/DIGImend/digimend-kernel-drivers/issues/182#issuecomment-581697592) that my driver also didn't work for him, but he managed to fix it, maybe his version will also work for you?

**Comment by createskyblue** [comment]
Many thanks for your help to my friend

T503 is working

**Comment by createskyblue** [comment]
Thank you so much for your help, my friend

T503 has

**Comment by createskyblue** [comment]
Thank you so much for your help, my friend

T503 is working

**Comment by alex-s-v** [comment]
You are very welcome!
