### ISSUE TITLE
Adapting to support 10moons 1060 Plus tablet.

### ISSUE THREAD

**Issue by ghost** [alex-s-v/10moons-driver#6]
This driver seems to support the 1060Plus tablet, except that the X and Y pen axes are inverted.
I don't know much about drivers, but could one naively invert the code to get the correct X and Y positioning? I've tried messing with the following parts of the code and could only get one the X axis to work correctly.

```
pen_x = config['pen']['max_x'] - (data[5] * 255 + data[4])
pen_y = data[3] * 255 + data[2]
```

**Comment by alex-s-v** [comment]
Hello. If by "inverted" you mean that top-bottom and left-right directions are inverse then fix is rather simple.
```python
pen_x = data[5] * 255 + data[4]
pen_y = config['pen']['max_y'] - (data[3] * 255 + data[2])
```

**Comment by ghost** [comment]
Sorry, I worded it badly, I meant the X and Y axis being flipped around. Since moving my pen horizontally in the Y axis causes  movement in the X axis. Is this as easy to fix?

**Comment by alex-s-v** [comment]
Yes, it's even easier. Just swap variables for the X and Y axis, and that's all.
```python
pen_x = data[3] * 255 + data[2]
pen_y = config['pen']['max_y'] - (data[5] * 255 + data[4])
```
And if after that directions become inverted (as I initially thought) then you could use code in my first reply to fix it.

**Comment by ghost** [comment]
Thanks a lot, I got around to testing it and now it works perfectly.

**Comment by alex-s-v** [comment]
You're welcome
