### ISSUE TITLE
Possible error in x-axis and y-axis

### ISSUE THREAD

**Issue by neko205-mx** [alex-s-v/10moons-driver#7]
I want to know how to make the tablet swap the X and Y axis
He is opposite on my computer
.... I'm very sorry, I don't know much about python.

**Comment by alex-s-v** [comment]
Hello. I don't have the tablet with me right now, but I think that I managed to fix the problem with a new update.

This is from the readme file:
"If you find that using this driver with your tablet results in reverse axis or directions (or both), you can modify parameters swap_axis, swap_direction_x, and swap_direction_y by changing false to true and another way around." in config.yaml file.

If you can test it, and report back to me it would be great.

**Comment by alex-s-v** [comment]
I tested it and it works just fine.
