### ISSUE TITLE
Driver broken with Kernel 6.0.6-76060006-generic

### ISSUE THREAD

**Issue by abdelouahabb** [alex-s-v/10moons-driver#8]
Hi,
When using the driver with `6.0.6-76060006-generic` the machine freezes ! and the lonely solution is to restart ...

Solution : updating to the latest (time of writing) `6.0.9-060009-generic` solved the issue

**Comment by alex-s-v** [comment]
Hmm, I don't know what the cause of this issue, but I'm glad that it is no longer
